apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80 # in the container
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.4
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'root'
            - name: MYSQL_DATABASE
              value: 'laravel'
            - name: MYSQL_USER
              value: 'laravel'
            - name: MYSQL_PASSWORD
              value: 'laravel'
        - name: nginx
          image: underser/laravel-crm-nginx
        - name: php-fpm
          image: underser/laravel-crm:latest
          command: ['/bin/sh', '-c']
          args: ['php artisan migrate && php-fpm']
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 15
          env:
            - name: APP_ENV
              value: 'local'
            - name: APP_DEBUG
              value: 'true'
            - name: DB_CONNECTION
              value: 'mysql'
            - name: DB_HOST
              value: '127.0.0.1'
            - name: DB_PORT
              value: '3306'
            - name: DB_DATABASE
              value: 'laravel'
            - name: DB_USERNAME
              value: 'laravel'
            - name: DB_PASSWORD
              value: 'laravel'
            - name: APP_KEY
              value: 'base64:3m5Je886yBDvo0g9+q2wM/Z4rtrWcCnSxTi/slBMZEI='
