apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      #restartPolicy: Always
      containers:
        - name: nginx
          image: underser/laravel-crm-nginx
        - name: php-fpm
          image: underser/laravel-crm:latest
          #imagePullPolicy: Always
          command: ['/bin/sh', '-c']
          args: ['php artisan migrate --force && php-fpm']
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 15
          env:
            - name: APP_ENV
              value: 'staging'
            - name: APP_DEBUG
              value: 'true'
            - name: DB_CONNECTION
              value: 'mysql'
            - name: DB_HOST
              value: 'db-service.default'
            - name: DB_PORT
              value: '3306'
            - name: DB_DATABASE
              value: 'laravel'
            - name: DB_USERNAME
              value: 'laravel'
            - name: DB_PASSWORD
              value: 'Qzkm68aljhjkh'
            - name: APP_KEY
              value: 'base64:3m5Je886yBDvo0g9+q2wM/Z4rtrWcCnSxTi/slBMZEI='
