<?php
declare(strict_types=1);

namespace App\States\Project;

class DoneProjectState extends BaseProjectState
{
    public function closed(): void
    {
        parent::closed(); // TODO: Change the autogenerated stub
    }
}
