<?php
declare(strict_types=1);

namespace App\States\Project;

class EstimationProjectState extends BaseProjectState
{
    public function inProgress(): void
    {
        parent::inProgress(); // TODO: Change the autogenerated stub
    }
}
