<?php
declare(strict_types=1);

namespace App\States\Project;

class OpenProjectState extends BaseProjectState
{
    public function estimation(): void
    {
        parent::estimate(); // TODO: Change the autogenerated stub
    }
}
