<?php
declare(strict_types=1);

namespace App\States\Project;

class PostponeProjectState extends BaseProjectState
{
    public function inProgress(): void
    {
        parent::start(); // TODO: Change the autogenerated stub
    }

    public function closed(): void
    {
        parent::closed(); // TODO: Change the autogenerated stub
    }
}
