name: Main CI
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ ]

jobs:
    main:
        runs-on: ubuntu-latest
        services:
            db:
                image: mariadb:10.4
                ports:
                    - 3306:3306
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: testing
            es01:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
                env:
                    node.name: es01
                    cluster.name: es-docker-cluster
                    discovery.type: single-node
                    bootstrap.memory_lock: true
                    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
                ports:
                    - 9200:9200
        steps:
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
            - uses: actions/checkout@v3
            - name: Copy .env
              run: php -r "file_exists('.env') || copy('.env.example', '.env');"
            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist && npm install && npm run build
            - name: Generate key
              run: php artisan key:generate
            - name: Directory Permissions
              run: chmod -R 777 storage bootstrap/cache
            - name: Index models.
              run: php artisan scout:import 'App\Models\Project' && php artisan scout:import 'App\Models\Task'
              env:
                  DB_HOST: 127.0.0.1
                  DB_DATABASE: testing
                  DB_USERNAME: root
                  DB_PASSWORD: root
                  DB_PORT: ${{ job.services.db.ports['3306'] }}
                  SCOUT_DRIVER: elastic
            - name: Execute tests (Unit and Feature tests) via PHPUnit
              run: php artisan test --parallel
              env:
                  DB_HOST: 127.0.0.1
                  DB_PORT: ${{ job.services.db.ports['3306'] }}
                  SCOUT_DRIVER: elastic
